name: "Setup Backend Environment"
description: "Installs Python, uv and dependencies for the backend"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: 'backend/.python-version'
        cache: 'pip'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    
    - name: Prepare local environment for CI
      shell: bash
      run: |
        cd backend
        echo "Backend directory structure:"
        ls -la
        
        echo "Original pyproject.toml content:"
        cat pyproject.toml
        
        # Create CI version of pyproject.toml by commenting out the problematic lines
        awk '
        /\[tool\.uv\.sources\]/ {print "# " $0; next}
        /fastapi-sqlalchemy = \{ path =/ {print "# " $0; next}
        {print}
        ' pyproject.toml > pyproject.toml.ci
        mv pyproject.toml.ci pyproject.toml
        
        echo "Modified pyproject.toml content:"
        cat pyproject.toml
        
        # Install fastapi-sqlalchemy from PyPI
        echo "Installing fastapi-sqlalchemy from PyPI"
        uv pip install fastapi-sqlalchemy==0.2.1
    
    - name: Install dependencies
      run: cd backend && uv sync --dev
      shell: bash 